markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Foresea"
markdown: rdiscount

author: "foresea"
atom-baseurl: "http://cxzhang.com"
disqus: "foresea.git"

navigations:
  - title: Archive
    class: fa fa-archive
    href: /archive.html
  - title: Translation
    class: fa fa-exchange
    href: /archive.html
  - title: Gallery
    class: fa fa-camera-retro
    href: http://cargocollective.com/foresea/
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

